fail_fast: true
repos:
  -
    repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      -
        id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-sfs
        args: [--max-line-length=120, --extend-ignore=SFS3 D107 SFS301 D100 D104 D401 SFS101 SFS201]

  -
    repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      -
        id: isort
